### ISSUE TITLE
Add pyproject.toml

### ISSUE THREAD

**Issue by femtotrader** [sgeisler/termgraph#10]
Hello,

`pyproject.toml` is the specified fileformat of [PEP 518](https://www.python.org/dev/peps/pep-0518/) for Build System Requirements of Python Projects.
Maybe adding such a file will help to turn this repository into a usable library (which could be installed using `pip install git+https://github.com/sgeisler/termgraph`)

Kind regards

PS : more info about pyproject.toml
https://stackoverflow.com/questions/62983756/what-is-pyproject-toml
https://snarky.ca/what-the-heck-is-pyproject-toml/
https://python-poetry.org/docs/pyproject/

**Comment by femtotrader** [comment]
I saw in https://github.com/sgeisler/termgraph/pull/9#issuecomment-774662201 that you are not "super familiar with the python ecosystem"... maybe you should have a look at [Poetry](https://python-poetry.org/)
This is a quite new way of managing dependencies (with isolated environments), generating packages, running tools such as [black](https://black.readthedocs.io/en/stable/) for code formating, integrating unit tests with tools such as [pytest](https://pytest.org/), integrating with code coverage tools, [PEP8](https://www.python.org/dev/peps/pep-0008/) checks with tools such as [flake8](https://flake8.pycqa.org/en/latest/) ...

https://dev.to/bowmanjd/getting-started-with-python-poetry-3ica
https://medium.com/georgian-impact-blog/python-tooling-makes-a-project-tick-181d567eea44

**Comment by sgeisler** [comment]
fixed in #9
