### ISSUE TITLE
implementing a bitcoin price server

### ISSUE THREAD

**Issue by sgeisler** [sgeisler/termgraph#3]
The server will:
 * listen as a simple TCP server (so one can use netcat as a client)
 * fetch the last transactions from bitstamp
 * render the candlestick graph (with user configurable sizes)
 * send it to the client

**Comment by femtotrader** [comment]
This should probably be out of the scope of this project.

**Comment by sgeisler** [comment]
Yeah, you are right, historically I wrote this library for the sole purpose of this but it turned out to be useful on its own :laughing:
