### ISSUE TITLE
Python 2.7

### ISSUE THREAD

**Issue by mbolder** [sgeisler/termgraph#5]
Hello, 
understanding that this might sound a bit backwards, but is there a chance for a 2.7 compatible version ? 

Regards

Markus

**Comment by akamensky** [comment]
Same here, it is weird that 2.7 is not supported since this is the most widely available version (on some systems you can't even upgrade... *looking at Mac OS*)

**Comment by sgeisler** [comment]
I know it might be annoying, but imho python 3 is the future. For example I'm using type annotations which are a feature of python 3.5 or 3.6 iirc. When my exams are over I will have a look at termgraph again, maybe I can build a version which works with python 2 as well.

**Comment by femtotrader** [comment]
https://www.python.org/dev/peps/pep-0373/ shows that Python 2.7 is not be maintained since 2020.

Maybe this issue should be closed
