### ISSUE TITLE
example_data in different order than expected

### ISSUE THREAD

**Issue by errnoh** [sgeisler/termgraph#8]
Example data is in `min, max, begin, end` but constructor expects `begin, max, min, end`. This results in the example graphs displaying all bars as green (min < max in all cases).

I'd submit a PR, but there's one issue. One could either change the order of the example data or one could change the constructor. My opinion would be that the constructor has weird order and should be changed, but that would break backwards compatibility for people who are already using this.

EDIT: Ah, right. The constructor is ordered as OHLC, I get it now. The example data should still be changed though.

**Comment by sgeisler** [comment]
Sorry, this is probably fallout from #7. Feel free to fix, I should have paid more attention. I'm not really from finance and took the authors word for it that OHLC is more standard.

**Comment by sgeisler** [comment]
I went ahead and opened #8, thx for the report. I'll merge soon, but wanted to give you the ability to respond in case I missed something.

**Comment by errnoh** [comment]
Just tested the PR (#9) and data looks fine now :) Mainly just commented about it since my initial thought was that the coloring logic was broken until I noticed that it's actually just data order that's different than expected.

Thanks for fixing it, likely could cause confusion to others as well
